### ISSUE TITLE
Cannot sign up or log in after logging out

### ISSUE THREAD

**Issue by peterweckend** [peterweckend/group-project-cmput404#119]
![image](https://user-images.githubusercontent.com/22946257/55417979-f2b02f00-552e-11e9-8f86-034e30097078.png)

Interestingly, if you move your mouse to the place where the login/signup buttons normally are, you can click them. They're just hidden or something.

They do show up in incognito mode.

**Comment by tiakindele** [comment]
check if this is fixed with my latest PR
