### ISSUE TITLE
Sign Up page changes

### ISSUE THREAD

**Issue by peterweckend** [peterweckend/group-project-cmput404#129]
can we add the first name and last name fields to it? Also it has a “github id” field, but can we replace that with a “github url” and “github username” field? finally, can we have stars next to the required fields

**Comment by peterweckend** [comment]
Also add a bio field to the edit and sign up pages if possible

**Comment by tiakindele** [comment]
@peterweckend pushed to PR

**Comment by tiakindele** [comment]
working on the bio part now
