### ISSUE TITLE
display post on View Post page in the correct time zone. Comments on posts don't use the correct time zone either

### ISSUE THREAD

**Issue by peterweckend** [peterweckend/group-project-cmput404#136]
right now, they're displaying in UTC time. They should be in MST time like how the home page does it

**Comment by tiakindele** [comment]
yeaaaaa... about that. the timezone thing keeps breaking some pages so i took it out of those pages. not sure how to fix..

**Comment by peterweckend** [comment]
im sure its no big deal. I doubt anyone would notice that, we can probably skip this one since we don't have much time?

**Comment by peterweckend** [comment]
comments are fixed
