### ISSUE TITLE
Separate Unlisted from other privacy settings

### ISSUE THREAD

**Issue by peterweckend** [peterweckend/group-project-cmput404#69]
Unlisted isn't one of the privacy settings. A post can be unlisted but also be public. Or unlisted and only visible to friends. 

See https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1145974 for more information.

Change the create a post form and the database to allow for the post to be unlisted or not, and also have a separate privacy setting.

**Comment by tiakindele** [comment]
done and pushed to my ui improvements branch
