### ISSUE TITLE
Filter posts for "Private to my server" privacy setting

### ISSUE THREAD

**Issue by peterweckend** [peterweckend/group-project-cmput404#71]
From "As a server admin, I want to share or not share posts with users on other servers."

I'm still not sure how this one works - ie whether it should be another category along with "friends" "public" "private", etc or if it needs to be its own boolean value. I suspect it needs to be another category because of this comment in the example-article.json file:

> # visibility ["PUBLIC","FOAF","FRIENDS","PRIVATE","SERVERONLY"]
I think SERVERONLY means public only to your server?? Will have to ask the prof

**Comment by peterweckend** [comment]
additional info from example-article.json i forgot to add:
"# for visibility PUBLIC means it is open to the wild web
			# FOAF means it is only visible to Friends of A Friend
			# If any of my friends are your friends I can see the post
			# FRIENDS means if we're direct friends I can see the post
			# PRIVATE means only you can see the post
			# SERVERONLY means only those on your server (your home server) can see the post
			# PRIVATE means only authors listed in "visibleTo" can see the post
                        "unlisted":false
                        # unlisted means it is public if you know the post name -- use this for images, it's so images don't show up in timelines"

**Comment by peterweckend** [comment]
UPDATE:
SERVERONLY means the post is public for everyone as long as they're on your home server. A post cannot have both SERVERONLY visibility and another type of visibility. For example, a post cannot be limited to your server AND private to friends.

**Comment by bhlewka** [comment]
So server only is just public to connectify users only basically

**Comment by peterweckend** [comment]
correct

**Comment by peterweckend** [comment]
**there's also a user story that says "As an author, posts I create be private to only friends on my host". I'm waiting to hear back from the TA if this is the same thing as SERVERONLY

**Comment by tiakindele** [comment]
added to the front end. all that's left is filtering the posts by server.

we could track the host of the post or the user

**Comment by tiakindele** [comment]
fixed
